// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: grpcapi/grpcapi.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type VerifySignaturesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageReference string `protobuf:"bytes,1,opt,name=imageReference,proto3" json:"imageReference,omitempty"`
	PublicKey      string `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
}

func (x *VerifySignaturesRequest) Reset() {
	*x = VerifySignaturesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcapi_grpcapi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifySignaturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySignaturesRequest) ProtoMessage() {}

func (x *VerifySignaturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_grpcapi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySignaturesRequest.ProtoReflect.Descriptor instead.
func (*VerifySignaturesRequest) Descriptor() ([]byte, []int) {
	return file_grpcapi_grpcapi_proto_rawDescGZIP(), []int{0}
}

func (x *VerifySignaturesRequest) GetImageReference() string {
	if x != nil {
		return x.ImageReference
	}
	return ""
}

func (x *VerifySignaturesRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

// The response message containing the greetings
type VerifySignaturesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signed bool `protobuf:"varint,1,opt,name=signed,proto3" json:"signed,omitempty"`
}

func (x *VerifySignaturesReply) Reset() {
	*x = VerifySignaturesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcapi_grpcapi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifySignaturesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySignaturesReply) ProtoMessage() {}

func (x *VerifySignaturesReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_grpcapi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySignaturesReply.ProtoReflect.Descriptor instead.
func (*VerifySignaturesReply) Descriptor() ([]byte, []int) {
	return file_grpcapi_grpcapi_proto_rawDescGZIP(), []int{1}
}

func (x *VerifySignaturesReply) GetSigned() bool {
	if x != nil {
		return x.Signed
	}
	return false
}

var File_grpcapi_grpcapi_proto protoreflect.FileDescriptor

var file_grpcapi_grpcapi_proto_rawDesc = []byte{
	0x0a, 0x15, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69,
	0x22, 0x5f, 0x0a, 0x17, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x22, 0x2f, 0x0a, 0x15, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x69,
	0x67, 0x6e, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x64, 0x32, 0x66, 0x0a, 0x0c, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x56, 0x0a, 0x10, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x20, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69,
	0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x61,
	0x70, 0x69, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x2f, 0x5a, 0x2d, 0x6c, 0x6f,
	0x63, 0x61, 0x6c, 0x2d, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2f,
	0x63, 0x6f, 0x73, 0x69, 0x67, 0x6e, 0x2d, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_grpcapi_grpcapi_proto_rawDescOnce sync.Once
	file_grpcapi_grpcapi_proto_rawDescData = file_grpcapi_grpcapi_proto_rawDesc
)

func file_grpcapi_grpcapi_proto_rawDescGZIP() []byte {
	file_grpcapi_grpcapi_proto_rawDescOnce.Do(func() {
		file_grpcapi_grpcapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcapi_grpcapi_proto_rawDescData)
	})
	return file_grpcapi_grpcapi_proto_rawDescData
}

var file_grpcapi_grpcapi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpcapi_grpcapi_proto_goTypes = []interface{}{
	(*VerifySignaturesRequest)(nil), // 0: grpcapi.VerifySignaturesRequest
	(*VerifySignaturesReply)(nil),   // 1: grpcapi.VerifySignaturesReply
}
var file_grpcapi_grpcapi_proto_depIdxs = []int32{
	0, // 0: grpcapi.Verification.VerifySignatures:input_type -> grpcapi.VerifySignaturesRequest
	1, // 1: grpcapi.Verification.VerifySignatures:output_type -> grpcapi.VerifySignaturesReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpcapi_grpcapi_proto_init() }
func file_grpcapi_grpcapi_proto_init() {
	if File_grpcapi_grpcapi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpcapi_grpcapi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifySignaturesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcapi_grpcapi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifySignaturesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcapi_grpcapi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcapi_grpcapi_proto_goTypes,
		DependencyIndexes: file_grpcapi_grpcapi_proto_depIdxs,
		MessageInfos:      file_grpcapi_grpcapi_proto_msgTypes,
	}.Build()
	File_grpcapi_grpcapi_proto = out.File
	file_grpcapi_grpcapi_proto_rawDesc = nil
	file_grpcapi_grpcapi_proto_goTypes = nil
	file_grpcapi_grpcapi_proto_depIdxs = nil
}
