// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: grpcapi/grpcapi.proto

package grpcapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SignatureVerificationClient is the client API for SignatureVerification service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignatureVerificationClient interface {
	VerifySignatures(ctx context.Context, in *VerifySignaturesRequest, opts ...grpc.CallOption) (*VerifySignaturesReply, error)
}

type signatureVerificationClient struct {
	cc grpc.ClientConnInterface
}

func NewSignatureVerificationClient(cc grpc.ClientConnInterface) SignatureVerificationClient {
	return &signatureVerificationClient{cc}
}

func (c *signatureVerificationClient) VerifySignatures(ctx context.Context, in *VerifySignaturesRequest, opts ...grpc.CallOption) (*VerifySignaturesReply, error) {
	out := new(VerifySignaturesReply)
	err := c.cc.Invoke(ctx, "/grpcapi.SignatureVerification/VerifySignatures", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignatureVerificationServer is the server API for SignatureVerification service.
// All implementations must embed UnimplementedSignatureVerificationServer
// for forward compatibility
type SignatureVerificationServer interface {
	VerifySignatures(context.Context, *VerifySignaturesRequest) (*VerifySignaturesReply, error)
	mustEmbedUnimplementedSignatureVerificationServer()
}

// UnimplementedSignatureVerificationServer must be embedded to have forward compatible implementations.
type UnimplementedSignatureVerificationServer struct {
}

func (UnimplementedSignatureVerificationServer) VerifySignatures(context.Context, *VerifySignaturesRequest) (*VerifySignaturesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifySignatures not implemented")
}
func (UnimplementedSignatureVerificationServer) mustEmbedUnimplementedSignatureVerificationServer() {}

// UnsafeSignatureVerificationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignatureVerificationServer will
// result in compilation errors.
type UnsafeSignatureVerificationServer interface {
	mustEmbedUnimplementedSignatureVerificationServer()
}

func RegisterSignatureVerificationServer(s grpc.ServiceRegistrar, srv SignatureVerificationServer) {
	s.RegisterService(&SignatureVerification_ServiceDesc, srv)
}

func _SignatureVerification_VerifySignatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySignaturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignatureVerificationServer).VerifySignatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.SignatureVerification/VerifySignatures",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignatureVerificationServer).VerifySignatures(ctx, req.(*VerifySignaturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SignatureVerification_ServiceDesc is the grpc.ServiceDesc for SignatureVerification service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SignatureVerification_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.SignatureVerification",
	HandlerType: (*SignatureVerificationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifySignatures",
			Handler:    _SignatureVerification_VerifySignatures_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcapi/grpcapi.proto",
}
